auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: Frank.com
url: http://jinglefun.github.io/
feed: /atom.xml
author_info: <a href="http://jinglefun.github.io/">FrankJin</a>
